### ISSUE TITLE
Content for about section

### ISSUE THREAD

**Issue by championshuttler** [Moz-NIEC/Streethack#5]
We need to write some content for about section for website which will consist all details about hackathon and venue

**Comment by championshuttler** [comment]
@chocos10 @g33kyshivam please take a look on it

**Comment by Varun-Malhan** [comment]
@championshuttler provide the necessary details for the content to be published.

**Comment by championshuttler** [comment]
@Varun-Malhan you can check more about hackathon here. http://ultrahack.org/ultrahackindia

**Comment by championshuttler** [comment]
Done with #27
